name: moeos
description: Opiniated Kinoite
base-image: registry.fedoraproject.org/fedora-kinoite
image-version: 42
modules: 
  - type: bling
    install:
      - negativo17
  - type: dnf
    repos:
      files:
        - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-%OS_VERSION%/errornointernet-klassy-fedora-%OS_VERSION%.repo
        - https://download.opensuse.org/repositories/home:/luisbocanegra/Fedora_Rawhide/home:luisbocanegra.repo
        - https://copr.fedorainfracloud.org/coprs/vulongm/vk-hdr-layer/repo/fedora-%OS_VERSION%/vulongm-vk-hdr-layer-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/birkch/Koi/repo/fedora-%OS_VERSION%/birkch-Koi-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/sneed/amd-color/repo/fedora-%OS_VERSION%/sneed-amd-color-fedora-%OS_VERSION%.repo
        - https://copr.fedorainfracloud.org/coprs/ilyaz/LACT/repo/fedora-%OS_VERSION%/ilyaz-LACT-fedora-%OS_VERSION%.repo
    install:
      packages:
        - steam
        - steam-devices
        - gamescope
        - mangohud
        - kde-material-you-colors
        - klassy
        - vk-hdr-layer
        - fastfetch
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
        - lact
        - adwaita-fonts-all
    remove:
      packages:
        - firefox
        - firefox-langpacks
  - type: default-flatpaks
    system:
      repo-url: https://dl.flathub.org/repo/flathub.flatpakrepo
      repo-name: flathub
      repo-title: "Flathub (System)"
      install:
        - com.borgbase.Vorta
        - com.discordapp.Discord
        - com.github.IsmaelMartinez.teams_for_linux
        - net.davidotek.pupgui2
        - org.kde.elisa
        - org.kde.gwenview
        - org.kde.haruna
        - org.kde.isoimagewriter
        - org.kde.kate
        - org.kde.kcolorchooser
        - org.kde.kdenlive
        - org.kde.kdf
        - org.kde.kolourpaint
        - org.kde.krita
        - org.kde.okular
      
  - type: signing
