name: moeos
description: Opiniated Kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42
modules: 
  - type: bling
    install:
      - rpmfusion
  - type: rpm-ostree
    repos:
      - rpmfusion
    install:
      - steam
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-42/errornointernet-klassy-fedora-%OS_VERSION%.repo
    install:
      - klassy
  - type: signing
