name: moe.os
description: Opiniated Kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42
modules:        
  - type: rpm-ostree
    install:
      - steam
      - steam-devices
    remove:
      - firefox
      - firefox-langpacks 
  - type: rpm-ostree
    repos:
      - https://download.copr.fedorainfracloud.org/results/errornointernet/klassy/fedora-%OS_VERSION%-x86_64/
    install:
      - klassy
  - type: signing
