name: moeos
description: Opiniated Kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42
modules: 
  - type: bling
    install:
      - rpmfusion
      - negativo17
  - type: rpm-ostree
    install:
      - steam
      - steam-devices
  #- type: rpm-ostree
   # repo:
    #  - https://dl.google.com/linux/chrome/rpm/stable/x86_64
    #install:
    #  - google-chrome-stable
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-42/errornointernet-klassy-fedora-%OS_VERSION%.repo
    install:
      - klassy
  - type: signing
