name: moe.os
description: Opiniated Kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42
modules: 
  - type: rpm-ostree
    install:
      - https://mirrors.rpmfusion.org/nonfree/fedora/rpmfusion-nonfree-release-$(rpm -E %fedora).noarch.rpm
  - type: rpm-ostree
    repos:
      - https://negativo17.org/repos/fedora-steam.repo
    install:
      - steam
      - steam-devices
  - type: rpm-ostree
    repos:
      - https://download.copr.fedorainfracloud.org/results/errornointernet/klassy/fedora-%OS_VERSION%-x86_64/
    install:
      - klassy
  - type: signing
