name: moeos
description: Opiniated Kinoite
base-image: ghcr.io/ublue-os/kinoite-main
image-version: 42
modules: 
  - type: bling
    install:
      - negativo17
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/errornointernet/klassy/repo/fedora-%OS_VERSION%/errornointernet-klassy-fedora-%OS_VERSION%.repo
      - https://download.opensuse.org/repositories/home:/luisbocanegra/Fedora_Rawhide/home:luisbocanegra.repo
      - https://copr.fedorainfracloud.org/coprs/vulongm/vk-hdr-layer/repo/fedora-%OS_VERSION%/vulongm-vk-hdr-layer-fedora-%OS_VERSION%.repo
      - https://copr.fedorainfracloud.org/coprs/birkch/Koi/repo/fedora-%OS_VERSION%/birkch-Koi-fedora-%OS_VERSION%.repo
    install:
      - steam
      - steam-devices
      - gamescope
      - kde-material-you-colors
      - klassy
      - https://dl.google.com/linux/direct/google-chrome-stable_current_x86_64.rpm
      - vk-hdr-layer
    remove:
      - firefox
      - firefox-langpacks
  - type: default-flatpaks
    system:
    install:
      - com.borgbase.Vorta
      - com.discordapp.Discord
      - com.github.IsmaelMartinez.teams_for_linux
      - net.davidotek.pupgui2
      - org.kde.elisa
      - org.kde.gwenview
      - org.kde.haruna
      - org.kde.isoimagewriter
      - org.kde.kate
      - org.kde.kcolorchooser
      - org.kde.kdenlive
      - org.kde.kdf
      - org.kde.kjournaldbrowser
      - org.kde.kolourpaint
      - org.kde.krita
      - org.kde.okular
      
  - type: signing
